DROP TABLE TICKET;
DROP TABLE RESERVATION;
DROP TABLE EVENT;
DROP TABLE SALESCHANNEL;
DROP TABLE APPUSER;

CREATE TABLE APPUSER
(
	Id SERIAL NOT NULL,
	UserCode VARCHAR(20),
	Name VARCHAR(100),
	Email VARCHAR(100),
	PhoneNumber VARCHAR(20),
	CreatedAt TIMESTAMP,
	IsActive BOOL,
	PRIMARY KEY (Id)
);

CREATE TABLE SALESCHANNEL
(
	Id SERIAL NOT NULL,
	ChannelCode VARCHAR(20),
	Name VARCHAR(50),
	Type INT,
	ApiKey VARCHAR(50),
	IsActive BOOL,
	CreatedAt TIMESTAMP,
	PRIMARY KEY (Id)
);

CREATE TABLE EVENT
(
	Id SERIAL NOT NULL,
	EventCode VARCHAR(20),
	Name VARCHAR(50),
	Description VARCHAR(200),
	EventDate TIMESTAMP,
	Venue VARCHAR(50),
	TotalTickets INT,
	AvailableTickets INT,
	BasePrice DECIMAL(18,2),
	CreatedAt TIMESTAMP,
	IsActive BOOL,
	PRIMARY KEY (Id)
);

CREATE TABLE RESERVATION
(
	Id SERIAL NOT NULL,
	ReservationCode VARCHAR(20),
	UserId INT REFERENCES APPUSER(Id),
	EventId INT REFERENCES EVENT(Id),
	SalesChannelId INT REFERENCES SALESCHANNEL(Id),
	TicketQuantity INT,
	TotalAmount DECIMAL(18,2),
	Status INT,
	ReservedAt TIMESTAMP,
	ExpiresAt TIMESTAMP,
	ConfirmedAt TIMESTAMP,
	PRIMARY KEY (Id)
);

CREATE TABLE TICKET
(
	Id SERIAL NOT NULL,
	TicketCode VARCHAR(20),
	EventId INT REFERENCES EVENT(Id),
	ReservationId INT REFERENCES RESERVATION(Id),
	Status INT,
	Price DECIMAL (18,2),
	SeatNumber VARCHAR (20),
	CreatedAt TIMESTAMP,
	PRIMARY KEY (Id)
);